name: Publish Package

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build and Publish
        run: pnpm release
